### ISSUE TITLE
Feature Request: Add assume-unchanged as well

### ISSUE THREAD

**Issue by ahmednrana** [jellyedwards/gitsweep#13]
In certain cases assume unchanged is needed. If feasible please add that as well

https://stackoverflow.com/questions/13630849/git-difference-between-assume-unchanged-and-skip-worktree

**Comment by jellyedwards** [comment]
Hi, I've added it in the context menu in explorer:

![image](https://user-images.githubusercontent.com/14051992/162322347-d99ecd90-851c-4c05-ae4a-9ee657b45411.png)


 the default is still `--skip-worktree` when you use the button in the git window.
