### ISSUE TITLE
Feature request: Show files in Tree-View

### ISSUE THREAD

**Issue by soraphis** [jellyedwards/gitsweep#17]
I'm super glad I've found this, nice work!

I think it would be super handy to have the same tree-view option as for the Staged/Changes area.

**Comment by jellyedwards** [comment]
Thanks, glad you like it!

Do you mean group the items up by how they are ignored? So one drop down for excluded ones, another for skip-worktree and another for assume-unchanged.

Or would you like the GitSweep context menu available in the Staged/Changes window?

(I don't have much free time so I might be slow responding but thanks for the feedback!)

**Comment by soraphis** [comment]
currently all files are just a list of their item names, my Idea was that they have some form of indentation and grouping based on their file path

**Comment by jellyedwards** [comment]
Oh I get you, I think that would be neat, I'll see what I can do.

I might add it as an config option as the current form sorta matches the source control window.

**Comment by soraphis** [comment]
> as the current form sorta matches the source control window.

the source control can be toggled between "list view" and "tree view" :D

![Code_npLYFfWUow](https://user-images.githubusercontent.com/3066582/174826825-c4893b80-d761-4bfb-be6d-54e2a3626ce1.png)

**Comment by jellyedwards** [comment]
Didn't know that! :D I'll see if I can copy how that's done when I get the time

**Comment by jellyedwards** [comment]
Hey, would you like to try it out on the pre-release version please & let me know, there's a little list/tree toggle button in the top right of the window:

![image](https://user-images.githubusercontent.com/14051992/178842480-e791f450-d86d-4bcf-8e68-3e39d18def71.png)

Pre-release can be found in the extensions settings or on the page when you click on the extension...
![image](https://user-images.githubusercontent.com/14051992/178842271-63b4db8d-1ad5-410a-8a46-172da05e4625.png)

**Comment by jellyedwards** [comment]
It should be 0.0.15, doesn't look like it's updated the marketplace yet so just double-check

**Comment by soraphis** [comment]
works like a charm!
thank you very much!
