### ISSUE TITLE
Tag latest version

### ISSUE THREAD

**Issue by MatthieuBarthel** [jellyedwards/gitsweep#19]
Hey, many thanks for this great extension.

I would like to submit it to nixpkgs, but I would need the master to be tagged with the latest version (0.0.15).

May I ask you to do this?

**Comment by jellyedwards** [comment]
Hey Matthieu, no worries - I think I've done it there if you'd like to check

**Comment by MatthieuBarthel** [comment]
Great, thank you!

I submitted a pull request to nixpkgs: https://github.com/NixOS/nixpkgs/pull/201217

I will try to keep pushing updates, but of course if you have any interest to become package maintainer on nixpkgs you are more than welcome :)
